baseUrl: /
languageCode: en-us
theme: smol
paginate: 10
googleAnalytics: UA-35775134-5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false
  favicon: /icon/favicon.ico
  hideFooter: true

languages:
  en:
    languageName: English
    title: Milosz Kowal | Artisan
    keywords: ""
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Milosz Kowal
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: blog
          name: Blog
          url: /posts
