version: 2.1

jobs:
  # Tests
  whitespace_checks:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Trailing Whitespace Check"
          command: tests/check_trailing_whitespace.sh
      - run:
          name: "Trailing Newline Check"
          command: tests/check_trailing_newline.sh

  markdown_linting:
    docker:
      - image: davidanson/markdownlint-cli2:0.3.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Markdown Linting"
          command: tests/lint_markdown.sh

  build:
    docker:
      - image: peaceiris/hugo:v0.89.4
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Get submodules"
          command: git submodule update --init --remote --recursive
      - attach_workspace:
          at: ./
      - run:
          name: "Build site"
          command: "hugo --minify"
      - persist_to_workspace:
          root: ./
          paths:
            - "public"
            - "tests"

  lint_html:
    docker:
      - image: mtlynch/htmlproofer:latest
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Check HTML"
          command: tests/lint_html.sh

  netlify_deploy:
    docker:
      - image: cimg/node:16.13.1
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Install Netlify CLI"
          command: "npm install netlify-cli --save-dev"
      - run:
          name: "Deploy"
          command: DEBUG=* ./node_modules/.bin/netlify deploy --dir=public --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod

workflows:
  test:
    jobs:
      - whitespace_checks
      - markdown_linting
      - build
      - lint_html:
          requires:
            - build
  deploy:
    jobs:
      - build
      - netlify_deploy:
          requires:
            - build
          filters:
            branches:
              only: master
