name: Building Website

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  check_whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tests/check_trailing_whitespace.sh
      - run: tests/check_trailing_newline.sh
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tests/lint_markdown.sh
  google_analytics_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tests/check_google_analytics_token.sh
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.108.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Persist artifact
        uses: actions/upload-artifact@v3
        with:
          name: public_website
          path: |
            public/
            tests/
