name: Building Website

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  check_whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tests/check_trailing_whitespace.sh
      - run: tests/check_trailing_newline.sh
