name: Building Website

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  check_whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tests/check_trailing_whitespace.sh
      - run: tests/check_trailing_newline.sh
  lint_markdown:
    runs-on: ubuntu-latest
    container:
      image: davidanson/markdownlint-cli2:0.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: tests/lint_markdown.sh
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.108.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Persist artifact
        uses: actions/upload-artifact@v3
        with:
          name: public_website
          path: |
            public/
            tests/
  google_analytics_check:
    runs-on: ubuntu-latest
    needs: build_website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: public_website
      - run: tests/check_google_analytics_token.sh
  lint_html:
    runs-on: ubuntu-latest
    container:
      image: mtlynch/htmlproofer:3.15.0
    needs: build_website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Artifacts
        uses: actions/download-artifact@v3
        with:
          name: public_website
      - name: Check HTML
        run: tests/lint_html.sh
